name: linux/amd64

on:
  schedule:
    - cron: '0 8 * * THU'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Pull Latest Linux Base Image
        run: docker pull debian:buster-slim
      - name: Build Linux Image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./linux.Dockerfile
          tags: |
            lacledeslan/gamesvr-ioquake3:latest
            ghcr.io/lacledeslan/gamesvr-ioquake3:latest
          build-args: |
            BUILDNODE=GitHub (Run Number: ${{ github.run_number }} Run ID: ${{ github.run_id }})
            SOURCE_COMMIT=${{ github.sha }}
          no-cache: true
#      - name: Test Linux Image
#        run: docker run --rm lacledeslan/gamesvr-ioquake3:latest /app/ll-tests/gamesvr-ioquake3.sh
      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push to Docker HUB
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push lacledeslan/gamesvr-ioquake3:latest
      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        run: docker push ghcr.io/lacledeslan/gamesvr-ioquake3:latest
